app:
  name: rook-ceph-operator
  namespace: rook-ceph
  chart: rook-ceph
  chartRepo: https://charts.rook.io/release
  chartVersion: v1.18.8 # renovate: datasource=helm depName=rook-ceph registryUrl=https://charts.rook.io/release
  hasValues: true
  disableAutoSync: true
  podSecurityPrivileged: true
