apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: rook-ceph
      repoURL: https://charts.rook.io/release
      targetRevision: v1.15.8
      helm:
        valueFiles:
        - $values/infra/k8s/storage/rook-ceph-operator/values.yaml
    - repoURL: 'https://github.com/guilhermewolf/atoca.house'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: false  # Don't auto-prune storage operator
