---
# Application configuration for cross-seed
app:
  name: cross-seed
  namespace: cross-seed
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.5.0
  volsyncPrivileged: false
