apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchy-postgres-operator
  namespace: argocd
spec:
  destination:
    namespace: crunchy-postgres-operator
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: pgo
      repoURL: registry.developers.crunchydata.com/crunchydata
      targetRevision: 5.8.5
    - repoURL: 'https://github.com/guilhermewolf/atoca.house'
      targetRevision: HEAD
      path: infra/k8s/cluster-management/crunchy-postgres-operator/
      directory:
        exclude: '{application.yaml}'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
