apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fusion
  namespace: argocd
spec:
  destination:
    namespace: fusion
    server: https://kubernetes.default.svc
  project: applications
  sources:
    - chart: app-template
      repoURL: ghcr.io/bjw-s-labs/helm
      targetRevision: 4.5.0
      helm:
        releaseName: fusion
        valueFiles:
        - $values/apps/productivity/fusion/values.yaml
    - repoURL: 'https://github.com/guilhermewolf/atoca.house'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/guilhermewolf/atoca.house'
      targetRevision: HEAD
      path: apps/productivity/fusion/
      directory:
        exclude: '{application.yaml,values.yaml}'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      annotations:
        volsync.backube/privileged-movers: "true"