app:
  name: arc-systems
  namespace: arc-systems
  chart: gha-runner-scale-set-controller
  chartRepo: ghcr.io/actions/actions-runner-controller-charts
  chartVersion: 0.13.0
  disableAutoSync: true
