apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync-system
  namespace: argocd
spec:
  destination:
    namespace: volsync-system
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: volsync
      repoURL: https://backube.github.io/helm-charts/
      targetRevision: 0.14.0
      helm:
        valueFiles:
        - $values/infra/k8s/storage/volsync-system/values.yaml
    - repoURL: 'https://github.com/guilhermewolf/atoca.house'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/guilhermewolf/atoca.house'
      targetRevision: HEAD
      path: infra/k8s/storage/volsync-system
      directory:
        exclude: '{application.yaml,values.yaml}'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
