---
# Application configuration for gatus
app:
  name: gatus
  namespace: gatus
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=helm registryUrl=oci://ghcr.io/bjw-s-labs/helm depName=app-template
  chartVersion: 4.6.2
