---
# Application configuration for one-password
app:
  name: one-password
  namespace: one-password
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.6.2
