apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: one-password
  namespace: argocd
spec:
  destination:
    namespace: one-password
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: connect
      repoURL: https://1password.github.io/connect-helm-charts
      targetRevision: 1.17.1
      helm:
        releaseName: connect
        valueFiles:
        - $values/infra/k8s/security/one-password/values.yaml
    - repoURL: 'https://github.com/guilhermewolf/atoca.house'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/guilhermewolf/atoca.house'
      targetRevision: HEAD
      path: infra/k8s/security/one-password/
      directory:
        exclude: '{application.yaml,values.yaml}'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
