app:
  name: nvidia-device-plugin
  namespace: nvidia-device-plugin
  chart: nvidia-device-plugin
  chartRepo: https://nvidia.github.io/k8s-device-plugin
  chartVersion: 0.14.5
  hasValues: true
  disableAutoSync: true
