---
# Application configuration for twenty
app:
  name: twenty
  namespace: twenty
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.5.0
