---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-ed-key
  namespace: external-dns
spec:
  itemPath: "vaults/k8s/items/cloudflare-ed-key"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-email
  namespace: external-dns
spec:
  itemPath: "vaults/k8s/items/cloudflare-email"
