---
# Parent app that discovers all application-level monitoring apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-monitoring
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: https://github.com/guilhermewolf/atoca.house
    targetRevision: HEAD
    path: apps/monitoring
    directory:
      recurse: true
      include: '*/application.yaml'
      exclude: 'application.yaml'
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
