---
# Application configuration for Sonarr Anime
app:
  name: sonarr-anime
  namespace: sonarr-anime
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.5.0
  volsyncPrivileged: false
