---
# Application configuration for threadfin
app:
  name: threadfin
  namespace: threadfin
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 4.6.2
  volsyncPrivileged: false
