---
# Parent app that discovers all networking infrastructure apps
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-networking
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/guilhermewolf/atoca.house
    targetRevision: HEAD
    path: infra/k8s/networking
    directory:
      recurse: true
      include: '*/application.yaml'
      exclude: 'application.yaml'  # Don't include this parent app itself
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
