---
apiVersion: v1
kind: ConfigMap
metadata:
  name: &app homepage
  annotations:
    reloader.stakater.com/match: "true"
data:
  settings.yaml: |
    ---
    title: Dashboard
    theme: dark
    color: neutral
    useEqualHeights: true
    layout: # key by group name in services.yaml
      Apps & Services:
        style: row
        columns: 3
      Infrastructure:
        style: row
        columns: 3
      Monitoring:
        style: row
        columns: 3
      Storage:
        style: row
        columns: 3
      Databases:
        style: row
        columns: 3

  widgets.yaml: |
    ---
    # - logo:
    - kubernetes:
        cluster:
          show: false
          cpu: false
          memory: false
          showLabel: false
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: custom
        url: https://search.unlocked.link/search?q=
        target: _blank
        # focus: true # Optional, will set focus to the search bar on page load
    - openmeteo:
        label: Home # optional
        latitude: {{HOMEPAGE_VAR_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_LONGITUDE}}
        timezone: Europe/Amsterdam
        units: metric
        cache: 5 # Time in minutes to cache API responses, to stay within limits

  services.yaml: |
    ---
    - Streaming:
        - Jellyfin:
            href: https://jellyfin.atoca.house
            icon: jellyfin.png
            description: Media Streaming Server
        - Seerr:
            href: https://seerr.atoca.house
            icon: jellyseerr.png
            description: Media Request & Management for Plex
    - Productionivity:
        - Vikunja:
            href: https://vikunja.atoca.house
            icon: vikunja.png
            description: Task Management & To-Do Lists
        - n8n:
            href: https://n8n.atoca.house
            icon: n8n.png
            description: Workflow Automation Tool
        - Twenty:
            href: https://twenty.atoca.house
            icon: sh-twenty.png
            description: CRM & Contact Management
        - FileBrowser:
            href: https://filebrowser.atoca.house
            icon: filebrowser.png
            description: Web File Manager

    - Media Management:
        - Radarr:
            href: https://radarr.atoca.house
            icon: radarr.png
            description: Movie Collection Manager
        - Sonarr:
            href: https://sonarr.atoca.house
            icon: sonarr.png
            description: TV Show Collection Manager
        - Anime:
            href: https://anime.atoca.house
            icon: sonarr.png
            description: Anime Collection Manager
        - Bazarr:
            href: https://bazarr.atoca.house
            icon: bazarr.png
            description: Subtitle Management
        - qBittorrent:
            href: https://qbittorrent.atoca.house
            icon: qbittorrent.png
            description: Torrent Client
        - NZBGet:
            href: https://nzbget.atoca.house
            icon: nzbget.png
            description: Usenet Download Client
        - Qui:
            href: https://qui.atoca.house
            icon: qui.png
            description: Usenet Search Engine
        - Autobrr:
            href: https://autobrr.atoca.house
            icon: autobrr.png
            description: Automated Download Client Manager
        - SLSKD:
            href: https://slskd.atoca.house
            icon: slskd.png
            description: Soulseek Client Daemon

    - Apps & Services:
        - HomeAssistant:
            href: https://hass.atoca.house
            icon: home-assistant.png
            description: Smart Home Automation
        - Homebridge:
            href: https://homebridge.atoca.house
            icon: homebridge.png
            description: HomeKit Bridge for Smart Devices
        - Syncthing:
            href: https://syncthing.atoca.house
            icon: syncthing.png
            description: Continuous P2P (peer to peer) file synchronization between devices
        - Fusion:
            href: https://fusion.atoca.house
            icon: sh-fusion-rss.png
            description: RSS agregator
        -  The Lounge:
            href: https://thelounge.atoca.house
            icon: thelounge.png
            description: Web IRC Client

    - Infrastructure:
        - ArgoCD:
            href: https://argocd.atoca.house
            icon: argo-cd.png
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNT}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNEL}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_TOKEN}}
        - Headlamp:
            href: https://headlamp.atoca.house
            icon: headlamp.png
            description: Kubernetes Cluster Management
        - Unifi:
            href: https://unifi.atoca.house
            icon: unifi.png
            description: Network Management System

    - Monitoring:
        - Grafana:
            href: https://grafana.atoca.house
            icon: grafana.png
            description: Analytics & Monitoring Dashboard
            widget:
              type: grafana
              version: 2
              alerts: alertmanager
              url: https://grafana.atoca.house
              username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
              password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
        - Alertmanager:
            href: https://alertmanager.atoca.house
            icon: alertmanager.png
            description: Alert Management
        - Prometheus:
            href: https://prometheus.atoca.house
            icon: prometheus.png
            description: Metrics & Time Series Database
        - Gatus:
            href: https://status.atoca.house
            icon: gatus.png
            description: Uptime & Status Monitoring
        - UptimeKuma:
            href: https://uptimekuma.atoca.house
            icon: sh-uptime-kuma.png
            description: Uptime & Status Monitoring
        - VictoriaLogs:
            href: https://victorialogs.atoca.house
            icon: victorialogs.png
            description: Log Aggregation & Analysis

    - Storage:
        - MinIO:
            href: https://minio.atoca.house
            icon: minio.png
            description: High Performance Object Storage
        - Rook-Ceph:
            href: https://rook.atoca.house
            icon: ceph.png
            description: Distributed Storage System
        - Unraid:
            href: https://compartilhado.atoca.house
            icon: unraid.png
            description: NAS Operating System

    - Databases:
        - pgAdmin:
            href: https://pgadmin.atoca.house
            icon: pgadmin.png
            description: PostgreSQL Database Management
  bookmarks.yaml: |
    ---

  docker.yaml: |
    ---

  kubernetes.yaml: |
    ---
    mode: cluster
    ingress: false # manually configure services (above)
