---
# Application configuration for LLDAP
app:
  name: lldap
  namespace: lldap
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.6.2
