---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name compartilhado-node-exporter
spec:
  staticConfigs:
    - targets:
        - nas.atoca.house:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: smartctl-exporter
spec:
  staticConfigs:
    - targets:
        - nas.atoca.house:9633
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: smartctl-exporter
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name compartilhado-cadvisor
spec:
  staticConfigs:
    - targets:
        - nas.atoca.house:8083
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name hass-node-exporter
spec:
  staticConfigs:
    - targets:
        - hass.internal:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
