---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name compartilhado-node-exporter
spec:
  staticConfigs:
    - targets:
        - 192.168.40.160:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name compartilhado-cadvisor
spec:
  staticConfigs:
    - targets:
        - 192.168.40.160:8083
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name hass-node-exporter
spec:
  staticConfigs:
    - targets:
        - 192.168.40.22:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
