---
# Application configuration for dispatcharr
app:
  name: dispatcharr
  namespace: dispatcharr
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 4.6.2
  volsyncPrivileged: false
