---
controllers:
  dispatcharr:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      dispatcharr:
        image:
          repository: ghcr.io/dispatcharr/dispatcharr
          tag: 0.19.0
        env:
          DISPATCHARR_ENV: modular
          DISPATCHARR_LOG_LEVEL: info
          DISPATCHARR_PORT: &port 9191
          REDIS_HOST: dragonfly.dragonfly-cluster.svc.cluster.local
          REDIS_PORT: 6379
          POSTGRES_PORT: 5432
        envFrom:
          - secretRef:
              name: dispatcharr-db-secret
        resources:
          requests:
            cpu: 50m
            memory: 1Gi
            nvidia.com/gpu: 1
          limits:
            memory: 3Gi
            nvidia.com/gpu: 1
      celery:
        image:
          repository: ghcr.io/dispatcharr/dispatcharr
          tag: 0.19.0
        command:
          - /app/docker/entrypoint.celery.sh
        env:
          DISPATCHARR_ENV: modular
          DISPATCHARR_LOG_LEVEL: info
          REDIS_HOST: dragonfly.dragonfly-cluster.svc.cluster.local
          REDIS_PORT: 6379
          POSTGRES_PORT: 5432
          DJANGO_SETTINGS_MODULE: dispatcharr.settings
          PYTHONUNBUFFERED: "1"
        envFrom:
          - secretRef:
              name: dispatcharr-db-secret
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            memory: 1Gi

defaultPodOptions:
  annotations:
    k8s.v1.cni.cncf.io/networks: |-
      [{
        "name": "vpn",
        "namespace": "kube-system",
        "ips": ["192.168.90.17/24"],
        "mac": "6e:54:a1:7c:2b:90"
      }]
  hostUsers: false
  runtimeClassName: nvidia
  nodeSelector:
    node.kubernetes.io/gpu: "true"
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"

service:
  dispatcharr:
    controller: dispatcharr
    ports:
      http:
        port: *port

route:
  dispatcharr:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
        sectionName: https
    hostnames:
      - dispatcharr.atoca.house
    rules:
      - backendRefs:
          - name: dispatcharr
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 3Gi
    globalMounts:
      - path: /data

  tmpfs:
    type: emptyDir
    advancedMounts:
      dispatcharr:
        dispatcharr:
          - path: /tmp
            subPath: tmp
