---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
spec:
  endpoints:
    - port: grafana
      path: /metrics
      honorLabels: true
  jobLabel: grafana
  namespaceSelector:
    matchNames:
      - grafana
  selector:
    matchLabels:
      grafana.internal/instance: grafana
