---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-configmap
  namespace: kromgo
data:
  config.yaml: |
    metrics:
      - name: talos_version
        query: node_os_info{name="Talos"}
        label: version_id
        title: Talos

      - name: kubernetes_version
        query: kubernetes_build_info{service="kubernetes"}
        label: git_version
        title: Kubernetes

      - name: cluster_node_count
        query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
        colors:
          - { color: "green", min: 0, max: 9999 }
        title: Nodes

      - name: cluster_pod_count
        query: sum(kube_pod_status_phase{phase="Running"})
        colors:
          - { color: "green", min: 0, max: 9999 }
        title: Pods

      - name: cluster_cpu_usage
        query: round(100 - (avg(rate(node_cpu_seconds_total{mode="idle", instance!="hass.internal:9100", instance!="nas.internal:9100"}[5m])) * 100), 0.1)
        suffix: "%"
        colors:
          - { color: "green", min: 0, max: 35 }
          - { color: "orange", min: 36, max: 75 }
          - { color: "red", min: 76, max: 9999 }
        title: CPU

      - name: cluster_memory_usage
        query: round(sum(node_memory_MemTotal_bytes{instance!="hass.internal:9100", instance!="nas.internal:9100"} - node_memory_MemAvailable_bytes{instance!="hass.internal:9100", instance!="nas.internal:9100"}) / sum(node_memory_MemTotal_bytes{instance!="hass.internal:9100", instance!="nas.internal:9100"}) * 100, 0.1)
        suffix: "%"
        colors:
          - { color: green, min: 0, max: 35 }
          - { color: orange, min: 36, max: 75 }
          - { color: red, min: 76, max: 9999 }
        title: Memory

      - name: cluster_power_usage
        query: round(upsHighPrecOutputLoad, 0.1)
        suffix: "w"
        colors:
          - { color: "green", min: 0, max: 400 }
          - { color: "orange", min: 401, max: 750 }
          - { color: "red", min: 751, max: 9999 }
        title: Power

      - name: cluster_age_days
        query: round((time() - min(kube_node_created) ) / 86400)
        suffix: "d"
        colors:
          - { color: "green", min: 0, max: 180 }
          - { color: "orange", min: 181, max: 360 }
          - { color: "red", min: 361, max: 9999 }
        title: Age

      - name: cluster_uptime_days
        query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400)
        suffix: "d"
        colors:
          - { color: "green", min: 0, max: 180 }
          - { color: "orange", min: 181, max: 360 }
          - { color: "red", min: 361, max: 9999 }
        title: Uptime

      - name: nas_cpu_usage
        query: round(100 - (avg(rate(node_cpu_seconds_total{mode="idle", instance="nas.internal:9100"}[5m])) * 100), 0.1)
        suffix: "%"
        colors:
          - { color: "green", min: 0, max: 35 }
          - { color: "orange", min: 36, max: 75 }
          - { color: "red", min: 76, max: 9999 }
        title: CPU

      - name: nas_memory_usage
        query: round(sum(node_memory_MemTotal_bytes{instance="nas.internal:9100"} - node_memory_MemAvailable_bytes{instance="nas.internal:9100"}) / sum(node_memory_MemTotal_bytes{instance="nas.internal:9100"}) * 100, 0.1)
        suffix: "%"
        colors:
          - { color: green, min: 0, max: 35 }
          - { color: orange, min: 36, max: 75 }
          - { color: red, min: 76, max: 9999 }
        title: Memory

      - name: nas_uptime_days
        query: round((node_time_seconds{instance="nas.internal:9100",job="compartilhado-node-exporter"} - node_boot_time_seconds{instance="nas.internal:9100",job="compartilhado-node-exporter"}) / 86400)
        suffix: "d"
        colors:
          - { color: "green", min: 0, max: 180 }
          - { color: "orange", min: 181, max: 360 }
          - { color: "red", min: 361, max: 9999 }
        title: Uptime

      - name: nas_containers_count
        query: count(container_last_seen{instance="nas.internal:8083"})
        colors:
          - { color: "green", min: 0, max: 9999 }
        title: Containers

      - name: unraid_version
        query: node_os_info{id="unraid-os"}
        label: version_id
        title: Unraid

      - name: cluster_alert_count
        query: alertmanager_alerts{state="active"} - 1 # Ignore Watchdog
        colors:
          - {color: "green", min: 0, max: 0}
          - {color: "red", min: 1, max: 9999}
        title: Alerts
