---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: ceph-node-nfsmount-diskspace-warning
spec:
  matchers:
    - name: alertname
      matchType: '='
      value: CephNodeDiskspaceWarning
    - name: mountpoint
      matchType: '='
      value: /etc/nfsmount.conf
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: ceph-node-local-diskspace-warning
spec:
  matchers:
    - name: alertname
      matchType: '='
      value: CephNodeDiskspaceWarning
    - name: device
      value: /dev/nvme.*
      matchType: "=~"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: nas-memory-high-utilization
spec:
  matchers:
    - name: alertname
      matchType: '='
      value: NodeMemoryHighUtilization
    - name: instance
      matchType: '='
      value: nas.atoca.house:9100
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: keda-hpa-maxed-out
spec:
  matchers:
    - name: alertname
      matchType: '='
      value: KubeHpaMaxedOut
    - name: horizontalpodautoscaler
      value: keda-hpa-.*
      matchType: "=~"
