---
# Application configuration for amd-device-labeller
app:
  name: amd-device-labeller
  namespace: kube-system
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.5.0
  volsyncPrivileged: false
