---
# Application configuration for Flaresolverr
app:
  name: flaresolverr
  namespace: flaresolverr
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 4.5.0
  volsyncPrivileged: false
