---
# Application configuration for Homebridge
app:
  name: homebridge
  namespace: homebridge
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.6.2
  volsyncPrivileged: false
