---
# Application configuration for Homebridge
app:
  name: homebridge
  namespace: homebridge
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 4.5.0
  volsyncPrivileged: false
