---
# Application configuration for Recyclarr
app:
  name: recyclarr
  namespace: recyclarr
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.5.0
  volsyncPrivileged: false
