app:
  name: csi-driver-nfs
  namespace: kube-system
  chart: csi-driver-nfs
  chartRepo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  chartVersion: 4.13.1
  disableAutoSync: true
