---
# Application configuration for Bazarr
app:
  name: bazarr
  namespace: bazarr
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.6.2
  volsyncPrivileged: false
