---
# Application configuration for Bazarr
app:
  name: bazarr
  namespace: bazarr
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=helm registryUrl=oci://ghcr.io/bjw-s-labs/helm depName=app-template
  chartVersion: 4.6.2
  volsyncPrivileged: true
