apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ksgate
  namespace: argocd
spec:
  destination:
    namespace: ksgate
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: ksgate
      repoURL: ghcr.io/ksgate/charts
      targetRevision: 0.6.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true