---
# ApplicationSet for monitoring infrastructure
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-monitoring
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/guilhermewolf/atoca.house
        revision: HEAD
        files:
          - path: "infra/k8s/monitoring/*/app-config.yaml"
        ignoreMissingValueFiles: true
  template:
    metadata:
      name: '{{.app.name}}'
      namespace: argocd
    spec:
      project: infra
      destination:
        namespace: '{{.app.namespace}}'
        server: https://kubernetes.default.svc

      sources:
        - chart: '{{.app.chart}}'
          repoURL: '{{.app.chartRepo}}'
          targetRevision: '{{.app.chartVersion}}'
          helm:
            valueFiles:
              - $values/infra/k8s/monitoring/{{.app.name}}/values.yaml

        - repoURL: https://github.com/guilhermewolf/atoca.house
          targetRevision: HEAD
          ref: values

        - repoURL: https://github.com/guilhermewolf/atoca.house
          targetRevision: HEAD
          path: 'infra/k8s/monitoring/{{.app.name}}'
          directory:
            exclude: '{application.yaml,values.yaml,app-config.yaml}'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
