app:
  name: reloader
  namespace: reloader
  chart: reloader
  chartRepo: https://stakater.github.io/stakater-charts
  chartVersion: 2.2.7
  hasValues: true
  customIgnoreDifferences: true
  disableAutoSync: true
