app:
  name: rook-ceph-cluster
  namespace: rook-ceph
  chart: rook-ceph-cluster
  chartRepo: https://charts.rook.io/release
  chartVersion: v1.19.1 # renovate: datasource=helm depName=rook-ceph-cluster registryUrl=https://charts.rook.io/release
  hasValues: true
  disableAutoSync: true
  podSecurityPrivileged: true
