---
# Application configuration for qBittorrent
app:
  name: qbittorrent
  namespace: qbittorrent
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 4.5.0
  volsyncPrivileged: false
