apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-home-automation
  namespace: argocd
  labels:
    atoca.house: application
spec:
  project: app-of-apps
  source:
    path: apps/home-automation/
    repoURL: https://github.com/guilhermewolf/atoca.house
    targetRevision: HEAD
    directory:
      recurse: true
      include: '*/application.yaml'
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
