app:
  name: envoy-gateway
  namespace: envoy-gateway-system
  chart: gateway-helm
  chartRepo: oci://docker.io/envoyproxy
  chartVersion: v1.6.1 # renovate: datasource=helm depName=gateway-helm registryUrl=oci://docker.io/envoyproxy
  hasValues: true
  disableAutoSync: true
