app:
  name: metrics-server
  namespace: kube-system
  chart: metrics-server
  chartRepo: https://kubernetes-sigs.github.io/metrics-server/
  chartVersion: 3.13.0
  hasValues: true
  disableAutoSync: true
