---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: infralens
spec:
  hostnames:
    - infralens.atoca.house
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: atoca-house-internal
      namespace: kube-system
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: infralens-frontend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
