---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: garage-restore
  namespace: garage
spec:
  trigger:
    manual: restore-once
  restic:
    repository: garage-r2-secret
    copyMethod: Direct
    destinationPVC: garage
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
