---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: garage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: garage-secrets
    template:
      data:
        GARAGE_RPC_SECRET: "{{ .GARAGE_RPC_SECRET }}"
        GARAGE_ADMIN_TOKEN: "{{ .GARAGE_ADMIN_TOKEN }}"
        GARAGE_METRICS_TOKEN: "{{ .GARAGE_METRICS_TOKEN }}"
  dataFrom:
    - extract:
        key: garage-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-r2-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ .RESTIC_REPOSITORY }}/garage"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-r2
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
