---
# Application configuration for Radarr
app:
  name: radarr
  namespace: radarr
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.5.0
  volsyncPrivileged: false
