---
# Application configuration for Prowlarr
app:
  name: prowlarr
  namespace: prowlarr
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  # renovate: datasource=docker depName=ghcr.io/bjw-s-labs/helm/app-template
  chartVersion: 4.6.2
  volsyncPrivileged: true  # Requires privileged volsync movers
