---
namespace: k8tz
replicaCount: 2
timezone: Europe/Amsterdam
cronJobTimeZone: true
webhook:
  certManager:
    enabled: true
    issuerRef:
      name: k8tz-webhook-issuer
      kind: Issuer
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: k8tz
          topologyKey: kubernetes.io/hostname
